### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/net.oz9aec.Gpredict#14]
The Gpredict Flatpak does not seem to be actively maintained anymore. @sielicki I can help co-maintain the repo. Feel free to let me know. I already maintain other ham radio related apps on Flathub.

/cc @hfiguiere

**Comment by hfiguiere** [comment]
There is nothing I can do about inviting new maintainers. This is @barthalion prerogative.

**Comment by sielicki** [comment]
Asciiwolf is a name I recognize, he should be added.

**Comment by sielicki** [comment]
Finally on a computer I own and able to look into this -- nothing I can do on the repo settings from my end to add you. @barthalion   

Apologies for the lack of effort here / lack of bumps, just busy with day job, not much time for fun with radio.
